spring.profiles.active=dev
spring.application.name=InventarioService
server.port=8085

# Incluir detalles de error en la respuesta y logs
server.error.include-message=always
server.error.include-stacktrace=always

# Ruta para almacenar fotografías subidas (jpg, png)
photos.storage.location=uploads/photos

service.auto-register.authServiceUrl=${AUTH_SERVICE_URL:http://localhost:8082}
service.token-validation.auth-service-url=${AUTH_SERVICE_URL:http://localhost:8082}

app.frontend.url=${FRONTEND_URL:http://localhost:57681}