spring.datasource.url=jdbc:sqlite:db/farmacia.db
spring.datasource.driverClassName=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.actuate=DEBUG
spring.h2.console.enabled=false
spring.profiles.active=dev
server.port=8085