# =============================================
# Perfil: DESARROLLO (SQLite)
# =============================================
spring.datasource.url=jdbc:sqlite:db/farmacia.db
spring.datasource.driverClassName=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Logs detallados solo en desarrollo
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.actuate=DEBUG
logging.level.com.inventario=DEBUG
spring.mvc.log-request-details=true
